application: email2sms-7
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /
  script: home.py

- url: /store
  script: store.py

- url: /storeself
  script: store_self.py

libraries:
- name: webapp2
  version: "2.5.2"
