print "Content-type:text/html\r\n\r\n"
print "<h2>Usage Instructions: (Only for India)</h2><br />"
print "<h4>General Mode:</h4>"
print "Forward your mails to &lt;10-digit number&gt;@smsmafia.in<br/>Ex: 98595598595@smsmafia.in<br/>"
print "The SMS will be delivered on this number between 9 AM and 9 PM (only if it is Non-DND)<br/><br/>"
print "<h4>Special Mode:</h4>"
print "Create a way2sms.com account and "
print "Forward your mails to &lt;username&gt;_&lt;password&gt;@smsmafia.in<br/>Ex: 98595598595_thepassword@smsmafia.in<br/>"
print "The SMS will be delivered almost instantly and round the clock (subject to service availability of Way2sms.com)."